-- Russian Localization Module for Lord of Mysteries
-- Developed for LOM Mod Loader
local Russian = {
    Enabled = true,
    Version = "1.0.0",
}

-- Названия вкладок главного меню и навигации
Russian.shortMenuLabels = {
    Fashion = "Гардероб",
    Pastime = "Исследование",
    Dungeon = "Подземелья",
    PVP = "Арена",
    Equip = "Снаряжение",
    Skill = "Навыки",
    Talent = "Таланты",
    Promotion = "Путь",
    Sealed = "Реликвии",
    SecretPartner = "Марионетки",
    Fellow = "Союзники",
    Paotuan = "TRPG",
    Guild = "Клуб",
    Home = "Поместье",
    Task = "Задания",
    Family = "Семья",
    Qingyuan = "Связи",
    Achievement = "Достижения",
    Strategy = "Гайд",
    VideoCreation = "Творчество",
    Friend = "Друзья",
    ShadowCity = "Темный Город",
    Character = "Персонаж",
    HomePage = "Главная",
    Bag = "Инвентарь",
    Notice = "Новости",
    Email = "Почта",
    Rank = "Рейтинг",
    Detach = "Снять",
    Setting = "Настройки",
    QuitGame = "Выход",
}

-- Имена и способности марионеток
Russian.marionetteEnglishNames = {
    [87303350] = "Пришествие рассвета",
    [87303360] = "Клеймо арбитража",
    [87303370] = "Взор тайновидца",
    [87303380] = "Защита утреннего света",
    [87303390] = "Клятва рыцаря",
    [87303400] = "Одержимость духом бабочки",
    [87303410] = "Нисходящая тень",
    [87303420] = "Эхо погребального звона",
    [87303430] = "Серия когтей вожака",
    [87303440] = "Защита бура",
}

-- Системные константы и действия интерфейса
Russian.stringConstOverrides = {
    BAG_AUTO_AUTO_RESOLVE_TITLE = "Подтверждение авто-распыления",
    BAG_AUTO_DECOMPOSE_TITLE = "Настройки авто-распыления",
    COMMENT_PANEL_TITLE = "Комментарии",
    DIALOGUE_SKIP = "Пропустить",
    EQUIPMENT_PLAN_APPLY_CURRENT_PLAN = "Применить сборку",
    FASHION_APPEARANCE = "Внешний вид",
    FASHION_DYE_MY_PLAN = "Мои стили",
    GUILD_CARGO_HUB_REWARD_COMPLETE = "Получено",
    GVG_HONOR_CLAIMED_TEXT = "Получено",
    ITEM_GOT = "Получено",
    MONTH_CARD_MAIN_PAGE_TODAY_RECEIVED_LABEL = "(Получено сегодня)",
    FAMILY_INVITE_SHARE_TEAM = "Канал группы",
    FAMILY_INVITE_SHARE_WORLD = "Мировой канал",
    FAMILY_MEMBER_COUNT_FMT = "Члены семьи: %s/14",
    FAMILY_MEMBER_FMT = "Члены семьи (%d/%d)",
    ONE_CLICK_IN_USE = "Используется",
    ONE_CLICK_RECOMMEND_PLAN = "Рекомендованная сборка",
    ONE_CLICK_SHARE_RECOMMEND_PLAN = "Рекомендованные сборки",
    ONE_CLICK_TITLE = "Помощник в один клик",
    ONE_CLICK_USE = "Использовать",
    TRAINTRADE_ITEM_DISCOUNT_CHINESE = "Скидка %d0%%",
    MAP_PVP_LAST_HUNT_DRAGON_BOSS_BELONG_FORMAT = "Принадлежность команде: <Green>%s</>",
    MAP_PVP_LAST_HUNT_DRAGON_BOSS_NAME = "Проекция Дракона",
    MAP_PVP_LAST_HUNT_DRAGON_BOSS_NOT_BELONG_FORMAT = "Принадлежность команде: <Red>%s</>",
    PVP_LAST_HUNT_ACTIVE_TIME_FORMAT = "Активация через %M:%S",
    PVP_LAST_HUNT_ACTIVITY_NOT_OPEN_TEXT = "Используйте <Highlight>Семя Вздохов</>, чтобы пробудить Силу Вздохов, начать задание и получить ценные награды.",
    PVP_LAST_HUNT_ACTIVITY_OPEN_FORMAT = "Начало через %H ч. %M мин.",
    PVP_LAST_HUNT_ACTIVITY_OPEN_TEXT = "Время начала события",
    PVP_LAST_HUNT_ACTIVITY_REWARD_PREVIEW_FORMAT = "Награды за задание",
    PVP_LAST_HUNT_BOSS_BUTTON_DESC = "Перейти",
    PVP_LAST_HUNT_BOSS_CONTENT_DESC = "Описание Дракона Королевского Города",
    PVP_LAST_HUNT_BOSS_DETAIL_CONDITION_TITLE = "Статус возрождения",
    PVP_LAST_HUNT_BOSS_DETAIL_CONTENT = "Побеждайте элитных монстров ради ценных наград",
    PVP_LAST_HUNT_BOSS_DETAIL_NOT_SPAWNED = "Цель еще не появилась",
    PVP_LAST_HUNT_BOSS_DETAIL_SPAWNED = "Цель появилась на поле боя",
    PVP_LAST_HUNT_BOSS_DETAIL_TITLE = "Цель охоты",
    PVP_LAST_HUNT_BOSS_DRAGON_FORMAT = "Дракон появится через %M:%S",
    PVP_LAST_HUNT_BOSS_SECOND_TITLE = "Сразить Дракона Королевского Города",
    PVP_LAST_HUNT_BOSS_TAG_NAME = "Страж Королевского Города",
    PVP_LAST_HUNT_BOSS_TITLE = "Убийство Дракона",
    PVP_LAST_HUNT_CAMP_SUBMIT_FORMAT = "Точка сдачи: %s",
    PVP_LAST_HUNT_CHAT_BUTTON_TEXT = "Перейти",
    PVP_LAST_HUNT_CHAT_TITLE = "Горн",
    PVP_LAST_HUNT_CROSS_SERVER_SCORE_TITLE = "Боевые заслуги",
    PVP_LAST_HUNT_DETAIL_MY_DATA_TAB = "Мои данные",
    PVP_LAST_HUNT_DETAIL_RANK_TAB = "Рейтинг",
    PVP_LAST_HUNT_FIGHT_ASSISTANT_FORMAT = "%s потерпел поражение от %s в локации %s. Требуется поддержка!",
    PVP_LAST_HUNT_FIGHT_KILL_RESULT_FORMAT = "%s успешно одолел %s в %s!",
    PVP_LAST_HUNT_GUILD_ACTIVITY_DESC_TIPS = "Финальный рейд на Дракона <Highlight>[Аукцион команды]</>: %d/%d (в эту пятницу) в 19:10",
    PVP_LAST_HUNT_GUILD_NAME_FORMAT = "Клуб <Enemy_Name>%s</>",
    PVP_LAST_HUNT_HIGHER_DETAIL_CONTENT = "Зона повышенной сложности с множеством вышедших из-под контроля монстров",
    PVP_LAST_HUNT_HIGHER_DETAIL_NOT_OPENED_TITLE = "В данный момент закрыто",
    PVP_LAST_HUNT_HIGHER_DETAIL_OPENED_TIME = "Открыто ежедневно: 19:00-21:00\nДополнительно: суббота и воскресенье, 14:00-16:00",
    PVP_LAST_HUNT_HIGHER_DETAIL_TITLE_NAME = "Продвинутый уровень · Прилив",
    PVP_LAST_HUNT_HUD_PROGRESS_CURRENCY_FORMAT = "<Highlight>%s</>/%s",
    PVP_LAST_HUNT_HUD_PROGRESS_FORMAT = "<Highlight>%d</>/%d",
    PVP_LAST_HUNT_ITEM_CAN_NOT_USE = "Недостаточное количество",
    PVP_LAST_HUNT_LACK_USE_ITEM_PROP_COUNT_FORMAT = "Осталось попыток: %s",
    PVP_LAST_HUNT_MAIN_PROGRESS_TITLE = "Предпросмотр наград",
    PVP_LAST_HUNT_MAP_DETAIL_DESC = "Вход в телепорт зоны фракции",
    PVP_LAST_HUNT_MAP_ITEM_NAME = "Семя Вздохов · Зона Прилива Монстров",
    PVP_LAST_HUNT_MEMBER_COUNT_FORMAT = "(Члены группы: %d/%d)",
    PVP_LAST_HUNT_MONSTER_CANCEL_BUTTON_NAME = "Отмена",
    PVP_LAST_HUNT_MONSTER_DROP_REWARD_TEXT = "Шанс добычи с <HyperLink stylename=\"Clickable\" u=\"\">обычных монстров</>",
    PVP_LAST_HUNT_MONSTER_DROP_REWARD_UNDERLINE_TEXT = "Шанс добычи с <HyperLink stylename=\"Underline\" u=\"\">обычных монстров</>",
    PVP_LAST_HUNT_MONSTER_RECOMMEND_GROUP = "Рекомендуется рейд",
    PVP_LAST_HUNT_MONSTER_RECOMMEND_TEAM = "Рекомендуется группа",
    PVP_LAST_HUNT_MONSTER_SUMMON_BUTTON_NAME = "Призвать",
    PVP_LAST_HUNT_MONSTER_SUMMON_LEFT_COUNT_FORMAT = "Осталось призывов на этой неделе: %d",
    PVP_LAST_HUNT_NOT_OPENED_BUTTON_TEXT = "Доступно после начала события",
    PVP_LAST_HUNT_RANK_TAB_GUILD_NAME = "Клуб",
    PVP_LAST_HUNT_RANK_TAB_PERSONAL_NAME = "Личный",
    PVP_LAST_HUNT_RESURGENCE_TIPS = "Выберите точку возрождения и нажмите 'Перейти'",
    PVP_LAST_HUNT_RESURGENCE_TITLE = "Выбор точки возрождения",
    PVP_LAST_HUNT_REVIVE_BUTTON_NAME = "Возродиться",
    PVP_LAST_HUNT_REWARD_PREVIEW_TITLE = "Награды за задание",
    PVP_LAST_HUNT_SCORE_TITLE = "Очки рейтинга",
    PVP_LAST_HUNT_SEND_BUTTON_TITLE = "Подать сигнал в горн",
    PVP_LAST_HUNT_SEND_CHAT_DEFAULT_TEXT = "Братья, на помощь!",
    PVP_LAST_HUNT_SEND_DEFAULT_TIP_TEXT = "Призыв до %d игроков",
    PVP_LAST_HUNT_SEND_PANEL_TIPS = "Призыв до 14 игроков",
    PVP_LAST_HUNT_SEND_PANEL_TITLE = "Зов горна",
    PVP_LAST_HUNT_SETTLE_MENT_ASSIST_NUM_TITLE = "Помощь",
    PVP_LAST_HUNT_SETTLE_MENT_CANCEL = "Отмена",
    PVP_LAST_HUNT_SETTLE_MENT_KILL_NUM_TITLE = "Убийства",
    PVP_LAST_HUNT_SETTLE_MENT_LEAVE = "Покинуть поле боя",
    PVP_LAST_HUNT_SETTLE_MENT_PROGRESS_NUM_TITLE = "Итоги охоты",
    PVP_LAST_HUNT_SETTLE_MENT_SCORE_NUM_TITLE = "Очки рейтинга",
    PVP_LAST_HUNT_SETTLE_MENT_TITLE = "Итоги охоты",
    PVP_LAST_HUNT_SUBMIT_CONTENT = "Сдайте материалы Алого Реликта в обмен на Охотничьи Ваучеры",
    PVP_LAST_HUNT_SUBMIT_REFRESH_DESC = "Дворецкий Охоты меняет позицию каждые 30 минут. В ожесточенных боях дворецких появляется больше.",
    PVP_LAST_HUNT_SUBMIT_REFRESH_TITLE = "Правила обновления",
    PVP_LAST_HUNT_SUBMIT_TITLE = "Дворецкий Охоты",
    PVP_LAST_HUNT_SUMMON_AUTHOER_FORMAT = "(Призван игроком: %s)",
    PVP_LAST_HUNT_SUMMON_MONSTER_GET_NUM = "Получено попыток",
    PVP_LAST_HUNT_SUMMON_MONSTER_LACK_NUM = "Попыток на этой неделе больше нет. Зарабатывайте Ваучеры Охоты.",
    PVP_LAST_HUNT_TASK_BUFF_NAME = "Сила Вздохов",
    PVP_LAST_HUNT_TASK_COMMIT_TEXT = "Сдать",
    PVP_LAST_HUNT_TASK_FINISH_TITLE_TEXT = "Завершено",
    PVP_LAST_HUNT_TASK_FRAGMENT_NAME = "Осколок добычи",
    PVP_LAST_HUNT_TASK_NOT_ACTIVE_CONTENT_TEXT = "Используйте Семя Вздохов, побеждайте монстров или грабьте других игроков, чтобы добыть Осколки, и сдайте их Графу Порядка.",
    PVP_LAST_HUNT_TASK_NOT_ACTIVE_FINISH_TEXT = "Задание завершено. Найдите Графа Порядка, чтобы сдать осколки.",
    PVP_LAST_HUNT_TASK_NOT_ACTIVE_TEXT = "Не активно",
    PVP_LAST_HUNT_TASK_PROGRESS_TEXT = "Прогресс охоты",
    PVP_LAST_HUNT_TASK_PROP_TEXT = "Семя Вздохов",
    PVP_LAST_HUNT_TASK_QUICK_TEAM = "Быстрая группа",
    PVP_LAST_HUNT_TASK_TITLE_NAME = "Финальная Охота",
    PVP_LAST_HUNT_TITLE_DETAIL_NAME = "Подробнее",
    PVP_LAST_HUNT_TITLE_FOLD_NAME = "Свернуть",
    PVP_LAST_HUNT_USE_ITEM_NOT_ACTIVITY_OPEN_FORMAT = "Недоступно вне времени события. Время: <highlight>%s-%s</>",
    PVP_LAST_HUNT_USE_ITEM_PROP_DESC = "Использование Семени Вздохов...",
    PVP_LAST_HUNT_USE_TASK_TEXT_NAME = "Принять задание",
    RED_PACKET_ALREADY_RECEIVED = "Получено",
    SECRET_PARTNER_BTN_ALREADY_CHANGE_ACTOR_NAME = "Переключение",
    SECRET_PARTNER_BTN_CHANGE_ACTOR_NAME = "Сменить",
    SECRET_PARTNER_CANCEL_CHANGE_ACTOR = "Отменить смену",
    SECRET_PARTNER_CHANGE_ACTOR_TITLE = "Цель смены",
    SECRET_PARTNER_SKILL_TEXT = "Навык марионетки",
    SECRET_PARTNER_STAR_UP_TEXT_FORMAT = "Последовательность %d",
    SKILL_PRESET_TAB_1 = "Рекомендованные сборки",
    TASK_TRACE_DISTANCE = "м",
    TRINITY_ALL_TREASURE_HAVE_CLAIMED = "Все награды получены",
    TEAM_INVITE_SECRET_PARTNER_TITLE = "Применение иллюзии",
    UIAPPEARANCE_USE = "Надеть",
    UIAPPEARANCE_USING = "Надето",
}

-- Общие надписи UI, кнопки, статусы и диалоги
Russian.visibleTextExactOverrides = {
    ["机动"] = "Мобильность",
    ["射程"] = "Дальность",
    ["推理检定"] = "Проверка дедукции",
    ["线索"] = "Улика",
    ["跳过"] = "Пропустить",
    ["回顾"] = "История",
    ["截图"] = "Скриншот",
    ["点击空白区域关闭"] = "Нажмите в любом месте, чтобы закрыть",
    ["点击任意区域跳过"] = "Нажмите в любом месте, чтобы пропустить",
    ["恭喜获得"] = "Поздравляем с получением",
    ["转化"] = "Преобразовать",
    ["男子"] = "Мужчина",
    ["丑人"] = "Уродец",
    ["愚者"] = "Шут",
    ["“愚者”"] = "«Шут»",
    ["塞巴斯蒂安"] = "Себастьян",
    ["寒巴斯蒂安"] = "Себастьян",
    ["非凡评分"] = "Рейтинг Потустороннего",
    ["推荐非凡评分"] = "Рек. рейтинг Потустороннего",
    ["奖励预览"] = "Предпросмотр наград",
    ["目标点数"] = "Целевые очки",
    ["黎明降临"] = "Пришествие рассвета",
    ["仲裁烙印"] = "Клеймо арбитража",
    ["窥秘凝视"] = "Взор тайновидца",
    ["晨曦守护"] = "Защита утреннего света",
    ["骑士誓约"] = "Клятва рыцаря",
    ["蝶灵附身"] = "Одержимость духом бабочки",
    ["丧钟回响"] = "Эхо погребального звона",
    ["头狼连爪"] = "Серия когтей вожака",
    ["钻头守护"] = "Защита бура",
    ["未拥有"] = "Не получено",
    ["推荐方案"] = "Рекомендованные сборки",
    ["官方推荐方案"] = "Официальная сборка",
    ["我的方案"] = "Мои сборки",
    ["我要变强"] = "Усиление",
    ["要变强"] = "Усиление",
    ["已领取"] = "Получено",
    ["今日已领取"] = "Получено сегодня",
    ["奖励已领取"] = "Награда получена",
    ["已领取全部奖励"] = "Все награды получены",
    ["使用"] = "Использовать",
    ["使用中"] = "Используется",
    ["图鉴"] = "Кодекс",
    ["跟随卡萝，来到了工厂区。"] = "Следуйте за Кэрол в Заводской район.",
    ["全部重置"] = "Сбросить всё",
    ["装备方案"] = "Сборки снаряжения",
    ["自动分解"] = "Авто-распыление",
    ["获得方式"] = "Способ получения",
    ["下一级效果"] = "Эффект след. уровня",
    ["木桩训练"] = "Манекен для тренировки",
    ["一键辅助"] = "Помощник в один клик",
    ["家族任务"] = "Задания Семьи",
    ["你尚未加入任何家族"] = "Вы пока не состоите в Семье.",
    ["[队伍]"] = "[Группа]",
    ["【附身能力】"] = "[Способность одержимости]",
    ["请选择要使用【灵体之线】的对象"] = "Выберите цель для [Нитей духовного тела]",
    ["附身剩余时间"] = "Время одержимости",
    ["秘偶属性生效总览"] = "Обзор характеристик марионетки",
    ["本频道可用传音发言"] = "В этом канале можно передавать голос",
    ["本频道无法发言"] = "В этом канале нельзя писать",
    ["霍伊大学赛艇队招新！"] = "Набор в команду по гребле Университета Хой!",
    ["成员列表"] = "Список участников",
    ["俱乐部会长"] = "Президент Клуба",
    ["正式成员"] = "Основной участник",
    ["候补成员"] = "Кандидат",
    ["可预存"] = "Доступно для накопления",
    ["已预存"] = "Накоплено",
    ["新手"] = "Новичок",
    ["赛季剧情"] = "Сюжет сезона",
    ["当前进度："] = "Текущий прогресс:",
    ["当前进度:"] = "Текущий прогресс:",
    ["击杀"] = "Убийства",
    ["助攻"] = "Помощь",
    ["排行榜"] = "Таблица лидеров",
    ["技能名称"] = "Название навыка",
    ["次数"] = "Количество",
    ["伤害量"] = "Урон",
    ["伤害来源"] = "Источник урона",
    ["寄售"] = "Комиссионка",
    ["终末猎杀"] = "Финальная Охота",
    ["主宰争锋"] = "Битва Владык",
    ["主宰之战"] = "Битва Владык",
    ["副本"] = "Подземелье",
    ["秩序世界"] = "Мир Порядка",
    ["本周获取上限"] = "Недельный лимит",
    ["城市暗面"] = "Темная сторона города",
    ["新"] = "Новое",
    ["对比"] = "Сравнить",
    ["进攻模式·PVP"] = "Атакующий режим · PvP",
    ["神圣之杖"] = "Священный посох",
    ["组队跟随中..."] = "Следуем за группой...",
    ["组队跟随中…"] = "Следуем за группой...",
    ["界面返回"] = "Назад",
    ["灵体之线玩法"] = "Нити духовного тела",
    ["廷根第一市民"] = "Первый гражданин Тингена",
    ["[封]"] = "[Запечатано]",
    ["狂袭式"] = "Яростный натиск",
    ["廷根守墓人"] = "Могильщик Тингена",
    ["机器加工厂坊"] = "Механический завод",
    ["总探索度"] = "Общее исследование",
    ["上限可累计至下周"] = "Остаток лимита переносится на след. неделю",
    ["安迪哥努斯笔记"] = "Записная книжка Антигона",
    ["首通队伍"] = "Первопроходцы",
    ["男子：（癫狂）万物的“母亲”，赐予我们新生！"] = "Мужчина: (В безумии) «Мать» всего сущего, даруй нам перерождение!",
    ["“愚者”：拿上这个。"] = "«Шут»: Возьми это.",
    ["丑人：（有效期十四年？为什么要签这么久的合同……）"] = "Уродец: (Срок действия 14 лет? Зачем подписывать контракт на столь долгий срок...)",
    ["弗莱"] = "Фрай",
    ["伦纳德"] = "Леонард",
    ["罗珊"] = "Розанна",
    ["没有太大危险了，不用特别在意。"] = "Опасности больше нет, не стоит волноваться.",
    ["罗珊小姐，这个铃铛是用来做什么的？"] = "Мисс Розанна, для чего нужен этот колокольчик?",
    ["三律之背反"] = "Антиномия Трёх Законов",
    ["镜像之自我"] = "Зеркальное «Я»",
}

-- Подмена фрагментов текста
Russian.visibleTextReplacements = {
    { "点击空白区域关闭", "Нажмите в любом месте, чтобы закрыть" },
    { "跳过", "Пропустить" },
    { "推荐非凡评分", "Рек. рейтинг Потустороннего" },
    { "非凡评分", "Рейтинг Потустороннего" },
    { "塞巴斯蒂安", "Себастьян" },
    { "寒巴斯蒂安", "Себастьян" },
    { "男子：", "Мужчина: " },
    { "丑人：", "Уродец: " },
    { "“愚者”：", "«Шут»: " },
    { "愚者", "Шут" },
    { "（癫狂）", "(В безумии) " },
    { "万物的“母亲”", "«Мать» всего сущего" },
    { "赐予我们新生", "даруй нам перерождение" },
    { "拿上这个", "Возьми это" },
    { "有效期十四年？为什么要签这么久的合同……", "Срок действия 14 лет? Зачем подписывать контракт на столь долгий срок..." },
    { "背包", "Инвентарь" },
    { "设置", "Настройки" },
    { "确定", "Подтвердить" },
    { "取消", "Отмена" },
}

-- Кэш и поиск в большой базе перевода
local russianRuntimeMap = nil
local russianRuntimeUnavailable = false

function Russian.lookupRussianText(chineseText)
    if not Russian.Enabled then return nil end

    -- 1. Сначала проверяем точные переопределения интерфейса
    local exact = Russian.visibleTextExactOverrides[chineseText]
    if exact then return exact end

    -- 2. Затем проверяем основной русский словарь диалогов и квестов
    if russianRuntimeMap == nil and not russianRuntimeUnavailable then
        local ok, loaded = pcall(require, "mods.cpdd_runtime_fixes.RuntimeTextRussian")
        if ok and type(loaded) == "table" then
            russianRuntimeMap = loaded
        else
            russianRuntimeUnavailable = true
        end
    end

    if russianRuntimeMap then
        local found = russianRuntimeMap[chineseText]
        if found then return found end
    end

    return nil
end

return Russian
