using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

class FinalizeAll206Entries
{
    static void Main()
    {
        Console.OutputEncoding = Encoding.UTF8;
        string ruPath = @"d:\gameDev\translate lotm\RuntimeTextRussian.lua";
        string remPath = @"d:\gameDev\translate lotm\tools\remaining_206.tsv";

        Console.WriteLine("=== FINISHING LAST 206 UNTRANSLATED STRINGS ===");

        var map = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // Formatting
            { "%d:%d", "%d:%d" },
            { "%d时%d分", "%d:%d" },
            { "%sx", "%sx" },
            { "%s倍", "%sx" },
            { "%s/%s/%s %s:%s", "%s/%s/%s %s:%s" },
            { "%s年%s月%s日 %s:%s", "%s/%s/%s %s:%s" },
            { "%s年%s月%s日 %s时%s分", "%s/%s/%s %s:%s" },
            { "%s %s %s", "%s %s %s" },
            { "%s第%s%s", "%s %s %s" },
            { "%", "%" },
            { "%时", "%" },
            { "<Double>%sx</>", "<Double>%sx</>" },
            { "<Double>%s倍</>", "<Double>%sx</>" },
            { "<Double>Double</>", "<Double>Двойной</>" },
            { "<Double>双倍</>", "<Double>Двойной</>" },
            { "<StandbyApplication>Extra</>", "<StandbyApplication>Дополнительно</>" },
            { "<StandbyApplication>额外</>", "<StandbyApplication>Дополнительно</>" },
            { "<h>Book</>", "<h>Книга</>" },
            { "<h>书籍</>", "<h>Книга</>" },

            // Beyonder tags
            { "< Hypnotist >", "<Гипнотизёр>" },
            { "<催眠师>", "<Гипнотизёр>" },
            { "<Avatar of Calamity>", "<Воплощение Бедствия>" },
            { "<天灾化身>", "<Воплощение Бедствия>" },
            { "< Guardian >", "<Страж>" },
            { "<守护者>", "<Страж>" },
            { "< Horror Bishop >", "<Епископ Ужаса>" },
            { "<恐惧主教>", "<Епископ Ужаса>" },
            { "< War Bishop >", "<Епископ Войны>" },
            { "<战争主教>", "<Епископ Войны>" },
            { "< Reaper >", "<Жнец>" },
            { "<收割者>", "<Жнец>" },
            { "< Instigator >", "<Подстрекатель>" },
            { "<教唆者>", "<Подстрекатель>" },
            { "<Unshadowed>", "<Бессолнечный>" },
            { "<无暗者>", "<Бессолнечный>" },
            { "< Fighter >", "<Боец>" },
            { "<格斗家>", "<Боец>" },
            { "< Silent Disciple >", "<Безмолвный Ученик>" },
            { "<沉默门徒>", "<Безмолвный Ученик>" },
            { "<Chaos Walker>", "<Странник Хаоса>" },
            { "<混乱行者>", "<Странник Хаоса>" },
            { "< Hand of God >", "<Рука Бога>" },
            { "<神明之手>", "<Рука Бога>" },
            { "< Matriarch of Desolation >", "<Мать Запустения>" },
            { "<荒芜主母>", "<Мать Запустения>" },
            { "<Spirit Medium>", "<Медиум>" },
            { "<通灵者>", "<Медиум>" },
            { "< Servant of Concealment >", "<Слуга Сокрытия>" },
            { "<隐秘之仆>", "<Слуга Сокрытия>" },
            { "< Wind Blessed >", "<Благословлённый Ветром>" },
            { "<风眷者>", "<Благословлённый Ветром>" },

            // Narrative & Lore
            { "Hornacis... Flegrea... Hornacis... Flegrea... Hornacis... Flegrea...", "Хорнакис... Флегреа... Хорнакис... Флегреа... Хорнакис... Флегреа..." },
            { "霍纳奇斯……弗雷格拉……霍纳奇斯……弗雷格拉……霍纳奇斯……弗雷格拉……", "Хорнакис... Флегреа... Хорнакис... Флегреа... Хорнакис... Флегреа..." },
            { "Planeswalker", "Странник" },
            { "旅法师", "Странник" },
            { "Gun Shadow Dash", "Призрачный рывок" },
            { "枪影疾行", "Призрачный рывок" },
            { "So\nGreedy", "Какая\nжадность" },
            { "真\r\n贪\r\n心", "Какая\r\nжадность" },
            { "W\r\nh\r\ny\r\n?", "П\r\nо\r\nч\r\nе\r\nм\r\nу\r\n?" },
            { "为\r\n什\r\n么\r\n？", "П\r\nо\r\nч\r\nе\r\nм\r\nу\r\n?" },
            { "MVP", "Лучший игрок (MVP)" },
            { "全场最佳", "Лучший игрок (MVP)" },
            { "WeChat Follow Gift", "Подарок за подписку" },
            { "企微关注礼", "Подарок за подписку" },
            { "Backline Gamble I", "Ставка огня I" },
            { "后排赌火 I", "Ставка огня I" },
            { "Backline Gambling Fire I", "Ставка огня I" },
            { "后排赌火I", "Ставка огня I" },
            { "Backline Gambling Fire II", "Ставка огня II" },
            { "后排赌火II", "Ставка огня II" },
            { "Custom_Dizzy", "Оглушение" },
            { "定制_头晕", "Оглушение" },
            { "RichText_TEST", "ФорматированныйТекст_ТЕСТ" },
            { "富文本_TEST", "ФорматированныйТекст_ТЕСТ" },
            { "Monster_Gold Coin", "Монстр: Золотые монеты" },
            { "怪物_金币", "Монстр: Золотые монеты" },
            { "Monster_Gold Coin Bullet", "Снаряд золотых монет" },
            { "怪物_金币子弹", "Снаряд золотых монет" },
            { "En", "Да" },
            { "恩", "Да" },
            { "Fighter_Bulwark", "Боец: Оплот" },
            { "拳手_壁垒", "Боец: Оплот" },
            { "Hint_Ring AOE", "Подсказка: кольцевая область" },
            { "提示_环形AOE", "Подсказка: кольцевая область" },
            { "Banish-Slow", "Изгнание — замедление" },
            { "放逐-减速", "Изгнание — замедление" },
            { "???", "???" },
            { "？？？", "???" },

            // Dialogs
            { "{{Young man, you have a sweet tongue. But talk is cheap. When you get tired of looking at them, how about buying me a drink? |You have a sweet tongue. It's a pity, the lights here never wait for anyone. }}", "{{Молодой человек, а вы умеете льстить. Но одних слов мало: когда устанете смотреть на них, угостите и меня выпивкой, как насчет этого?|А ты умеешь говорить приятные вещи. Жаль только, здешние огни никогда никого не ждут.}}" },
            { "{{年轻人，嘴还挺甜。但是光说没用，等你看她们看腻了，也请我一杯酒，如何？|你嘴真甜。可惜，这里的灯火，从来不等待任何人。 }}", "{{Молодой человек, а вы умеете льстить. Но одних слов мало: когда устанете смотреть на них, угостите и меня выпивкой, как насчет этого?|А ты умеешь говорить приятные вещи. Жаль только, здешние огни никогда никого не ждут.}}" },
            { "{{This handsome gentleman, you heard wrong. |This noble lady, you heard wrong. }}", "{{Красивый джентльмен, вы ослышались.|Благородная леди, вы ослышались.}}" },
            { "{{这位英俊的先生，你听错了。|这位尊贵的女士，你听错了。}}", "{{Красивый джентльмен, вы ослышались.|Благородная леди, вы ослышались.}}" },
            { "{Default is the data from the crazy table; if filled, it will overwrite the data in the table}", "{По умолчанию используются данные таблицы безумия; если заполнено, перезаписывает данные}" },
            { "{缺省就是crazy表的数据；如果填写了会覆写表格中的数据}", "{По умолчанию используются данные таблицы безумия; если заполнено, перезаписывает данные}" },

            // Notifications
            { "{\"id\":1000,\"title\":\"Download Paused\",\"body\":\"Your network environment has switched to mobile data, so the game download has been paused. We will automatically resume the download when you are on a WiFi connection.\",\"pushMode\":0,\"delayInSeconds\":1}", "{\"id\":1000,\"title\":\"Загрузка приостановлена\",\"body\":\"Сеть переключилась на мобильный интернет, загрузка приостановлена. Загрузка возобновится при подключении к Wi-Fi.\",\"pushMode\":0,\"delayInSeconds\":1}" },
            { "{\"id\":1000,\"title\":\"下载已暂停\",\"body\":\"由于您当前的网络环境切换至了流量环境，游戏已暂停下载，当您处于WiFi环境时，我们将自动为您恢复下载。\",\"pushMode\":0,\"delayInSeconds\":1}", "{\"id\":1000,\"title\":\"Загрузка приостановлена\",\"body\":\"Сеть переключилась на мобильный интернет, загрузка приостановлена. Загрузка возобновится при подключении к Wi-Fi.\",\"pushMode\":0,\"delayInSeconds\":1}" },
            { "{\"id\":1000,\"title\":\"Downloading Resources\",\"body\":\"Downloading in the background for you\",\"pushMode\":0,\"delayInSeconds\":1}", "{\"id\":1000,\"title\":\"Загрузка ресурсов\",\"body\":\"Загрузка ресурсов в фоновом режиме\",\"pushMode\":0,\"delayInSeconds\":1}" },
            { "{\"id\":1000,\"title\":\"正在下载资源\",\"body\":\"正在为您后台下载\",\"pushMode\":0,\"delayInSeconds\":1}", "{\"id\":1000,\"title\":\"Загрузка ресурсов\",\"body\":\"Загрузка ресурсов в фоновом режиме\",\"pushMode\":0,\"delayInSeconds\":1}" },
            { "{\"id\":1000,\"title\":\"Resource download failed\",\"body\":\"Download failed\",\"pushMode\":0,\"delayInSeconds\":1}", "{\"id\":1000,\"title\":\"Сбой загрузки ресурсов\",\"body\":\"Не удалось загрузить ресурсы\",\"pushMode\":0,\"delayInSeconds\":1}" },
            { "{\"id\":1000,\"title\":\"资源下载失败\",\"body\":\"下载失败\",\"pushMode\":0,\"delayInSeconds\":1}", "{\"id\":1000,\"title\":\"Сбой загрузки ресурсов\",\"body\":\"Не удалось загрузить ресурсы\",\"pushMode\":0,\"delayInSeconds\":1}" },
            { "{\"id\":1000,\"title\":\"Resource Download Complete\",\"body\":\"Download Complete\",\"pushMode\":0,\"delayInSeconds\":1}", "{\"id\":1000,\"title\":\"Загрузка ресурсов завершена\",\"body\":\"Загрузка ресурсов успешно завершена\",\"pushMode\":0,\"delayInSeconds\":1}" },
            { "{\"id\":1000,\"title\":\"资源下载完成\",\"body\":\"下载完成\",\"pushMode\":0,\"delayInSeconds\":1}", "{\"id\":1000,\"title\":\"Загрузка ресурсов завершена\",\"body\":\"Загрузка ресурсов успешно завершена\",\"pushMode\":0,\"delayInSeconds\":1}" },
            { "{\"notificationTitle\": \"Download Paused\",\"notificationContent\":\"Your network environment has switched to mobile data, so the game download has been paused. We will automatically resume the download when you are on a WiFi connection.\",\"showProgress\":false}", "{\"notificationTitle\": \"Загрузка приостановлена\",\"notificationContent\":\"Сеть переключилась на мобильный интернет, загрузка приостановлена. Загрузка возобновится при подключении к Wi-Fi.\",\"showProgress\":false}" },
            { "{\"notificationTitle\": \"下载已暂停\",\"notificationContent\":\"由于您当前的网络环境切换至了流量环境，游戏已暂停下载，当您处于WiFi环境时，我们将自动为您恢复下载。\",\"showProgress\":false}", "{\"notificationTitle\": \"Загрузка приостановлена\",\"notificationContent\":\"Сеть переключилась на мобильный интернет, загрузка приостановлена. Загрузка возобновится при подключении к Wi-Fi.\",\"showProgress\":false}" },
            { "{ \"notificationTitle\": \"Resource download failed\", \"notificationContent\": \"Download failed\", \"showProgress\": false }", "{ \"notificationTitle\": \"Сбой загрузки ресурсов\", \"notificationContent\": \"Не удалось загрузить ресурсы\", \"showProgress\": false }" },
            { "{\"notificationTitle\": \"资源下载失败\",\"notificationContent\":\"下载失败\",\"showProgress\":false}", "{ \"notificationTitle\": \"Сбой загрузки ресурсов\", \"notificationContent\": \"Не удалось загрузить ресурсы\", \"showProgress\": false }" },
            { "{\"notificationTitle\":\"Resource download complete\",\"notificationContent\":\"Download complete\",\"showProgress\":false}", "{\"notificationTitle\":\"Загрузка ресурсов завершена\",\"notificationContent\":\"Загрузка ресурсов успешно завершена\",\"showProgress\":false}" },
            { "{\"notificationTitle\":\"资源下载完成\",\"notificationContent\":\"下载完成\",\"showProgress\":false}", "{\"notificationTitle\":\"Загрузка ресурсов завершена\",\"notificationContent\":\"Загрузка ресурсов успешно завершена\",\"showProgress\":false}" },

            // Config schemas & combat params
            { "{\n \"No\": False, \n \"Yes\": True \n}", "{\n \"Нет\": False, \n \"Да\": True \n}" },
            { "{\n                        \"否\": False,\n                        \"是\": True,\n                    }", "{\n \"Нет\": False, \n \"Да\": True \n}" },
            { "{\n \"Light Attack\": \"LightHit\", \n \"Default Knockback\": \"HitBack\", \n \"Knockback 100cm_Control 0.3s\": \"HitBack_100_9F\", \n \"Knockback 200cm_Control 0.3s\": \"HitBack_200_9F\", \n \"Knockback 300cm_Control 0.3s\": \"HitBack_300_9F\", \n \"Knockdown\": \"HitDown\", \n \"Knockup\": \"HitFly\", \n \"Launch\": \"HitFloat\", \n \"Drag\": \"HitDrag\", \n \"Stiff Attack\": \"HitStiff\" \n}", "{\n \"Лёгкая атака\": \"LightHit\", \n \"Базовое отбрасывание\": \"HitBack\", \n \"Отбрасывание 100см_Контроль 0.3с\": \"HitBack_100_9F\", \n \"Отбрасывание 200см_Контроль 0.3с\": \"HitBack_200_9F\", \n \"Отбрасывание 300см_Контроль 0.3с\": \"HitBack_300_9F\", \n \"Сбивание с ног\": \"HitDown\", \n \"Подбрасывание\": \"HitFly\", \n \"Запуск\": \"HitFloat\", \n \"Притягивание\": \"HitDrag\", \n \"Оглушающая атака\": \"HitStiff\" \n}" },
            { "{\n                        \"轻攻击\": \"LightHit\",\n                        \"默认击退\": \"HitBack\",\n                        \"击退100cm_控制0.3秒\": \"HitBack_100_9F\",\n                        \"击退200cm_控制0.3秒\": \"HitBack_200_9F\",\n                        \"击退300cm_控制0.3秒\": \"HitBack_300_9F\",\n                        \"击倒\": \"HitDown\",\n                        \"击飞\": \"HitFly\",\n                        \"挑空\": \"HitFloat\",\n                        \"拖拽\": \"HitDrag\",\n                        \"僵直攻击\": \"HitStiff\"\n                    }", "{\n \"Лёгкая атака\": \"LightHit\", \n \"Базовое отбрасывание\": \"HitBack\", \n \"Отбрасывание 100см_Контроль 0.3с\": \"HitBack_100_9F\", \n \"Отбрасывание 200см_Контроль 0.3с\": \"HitBack_200_9F\", \n \"Отбрасывание 300см_Контроль 0.3с\": \"HitBack_300_9F\", \n \"Сбивание с ног\": \"HitDown\", \n \"Подбрасывание\": \"HitFly\", \n \"Запуск\": \"HitFloat\", \n \"Притягивание\": \"HitDrag\", \n \"Оглушающая атака\": \"HitStiff\" \n}" },
            { "{\n \"Light Attack\": \"LightHit\", \n \"Knockback\": \"HitBack\", \n \"Knockdown\": \"HitDown\", \n \"Knockup\": \"HitFly\", \n \"Launch\": \"HitFloat\", \n \"Drag\": \"HitDrag\", \n \"Stiff Attack\": \"HitStiff\", \n \"Boxing light hit\": \"BoxHitLight\", \n \"Boxing heavy hit\": \"BoxHitHeavy\" \n}", "{\n \"Лёгкая атака\": \"LightHit\", \n \"Отбрасывание\": \"HitBack\", \n \"Сбивание с ног\": \"HitDown\", \n \"Подбрасывание\": \"HitFly\", \n \"Запуск\": \"HitFloat\", \n \"Притягивание\": \"HitDrag\", \n \"Оглушающая атака\": \"HitStiff\", \n \"Бокс: лёгкий удар\": \"BoxHitLight\", \n \"Бокс: тяжёлый удар\": \"BoxHitHeavy\" \n}" },
            { "{\n    \"轻攻击\": \"LightHit\",\n    \"击退\": \"HitBack\",\n    \"击倒\": \"HitDown\",\n    \"击飞\": \"HitFly\",\n    \"挑空\": \"HitFloat\",\n    \"拖拽\": \"HitDrag\",\n    \"僵直攻击\": \"HitStiff\",\n    \"拳击玩法轻受击\": \"BoxHitLight\",\n    \"拳击玩法重受击\": \"BoxHitHeavy\"\n}", "{\n \"Лёгкая атака\": \"LightHit\", \n \"Отбрасывание\": \"HitBack\", \n \"Сбивание с ног\": \"HitDown\", \n \"Подбрасывание\": \"HitFly\", \n \"Запуск\": \"HitFloat\", \n \"Притягивание\": \"HitDrag\", \n \"Оглушающая атака\": \"HitStiff\", \n \"Бокс: лёгкий удар\": \"BoxHitLight\", \n \"Бокс: тяжёлый удар\": \"BoxHitHeavy\" \n}" },
            { "{\n\"Racing Gameplay\": \"0\"}", "{\n\"Гонки\": \"0\"}" },
            { "{\n  \"竞速玩法\": \"0\"}", "{\n\"Гонки\": \"0\"}" },
            { "{\n\"RUN\": \"0\",\n\"WALK\": \"1\",\n\"SPRINT\": \"2\"\n}", "{\n\"БЕГ\": \"0\",\n\"ШАГ\": \"1\",\n\"СПРИНТ\": \"2\"\n}" },
            { "{\n\"RUN\": \"0\",\n\"WALK\": \"1\",\n\"SPRINT(疾跑)\": \"2\"\n}", "{\n\"БЕГ\": \"0\",\n\"ШАГ\": \"1\",\n\"СПРИНТ\": \"2\"\n}" },
            { "{ \n \"Triple jump landing\": 0, \n \"x key landing\": 1 \n }", "{ \n \"Приземление тройного прыжка\": 0, \n \"Приземление клавишей X\": 1 \n }" },
            { "{\n\"三段跳落地\": 0,\n\"x 键落地\": 1\n}", "{ \n \"Приземление тройного прыжка\": 0, \n \"Приземление клавишей X\": 1 \n }" },
            { "{\n \"Upper layer passed LockTarget\": \"0\", \n \"Holder\": \"1\", \n \"Originator\": \"2\", \n \"Primary aggro target\": \"3\" \n}", "{\n \"Верхний слой передал LockTarget\": \"0\", \n \"Владелец\": \"1\", \n \"Инициатор\": \"2\", \n \"Основная цель агро\": \"3\" \n}" },
            { "{\n\"上层传入LockTarget\": \"0\",\n\"持有者\": \"1\",\n\"始作俑者\": \"2\",\n\"一仇目标\": \"3\"\n}", "{\n \"Верхний слой передал LockTarget\": \"0\", \n \"Владелец\": \"1\", \n \"Инициатор\": \"2\", \n \"Основная цель агро\": \"3\" \n}" },
            { "{\n \"Not specified\": \"\", \n \"All enemy players\": \"Enemy(Player)\", \n \"All enemy players (including corpses)\": \"Enemy(Player)(IncludeDead)\" \n}", "{\n \"Не указано\": \"\", \n \"Все вражеские игроки\": \"Enemy(Player)\", \n \"Все вражеские игроки (включая тела)\": \"Enemy(Player)(IncludeDead)\" \n}" },
            { "{\n\"不指定\":\"\",\n\"全体敌方玩家\": \"Enemy(Player)\",\n\"全体敌方玩家（包含尸体）\": \"Enemy(Player)(IncludeDead)\"\n}", "{\n \"Не указано\": \"\", \n \"Все вражеские игроки\": \"Enemy(Player)\", \n \"Все вражеские игроки (включая тела)\": \"Enemy(Player)(IncludeDead)\" \n}" },
            { "{\n \"Unspecified\": \"\", \n \"Hit target count (use this parameter after range hit in skills and spell fields)\": \"hitnum\", \n \"Filter target count (use this parameter when using target filtering)\": \"tarnum\", \n \"Class resource change value (including upward overflow value)\": \"propdiff\", \n \"Class resource change value (actual change value)\": \"proprealdiff\" \n}", "{\n \"Не указано\": \"\", \n \"Количество поражённых целей\": \"hitnum\", \n \"Количество отфильтрованных целей\": \"tarnum\", \n \"Изменение ресурса класса (с переполнением)\": \"propdiff\", \n \"Изменение ресурса класса (фактическое)\": \"proprealdiff\" \n}" },
            { "{\n\"不指定\":\"\",\n\"命中目标数（技能和法术场中的范围命中后使用该参数）\":\"hitnum\",\n\"筛选目标数（使用目标筛选时使用该参数）\": \"tarnum\",\n\"职业资源改变值（包括向上溢出值）\": \"propdiff\",\n\"职业资源改变值（实际改变值）\": \"proprealdiff\"\n}", "{\n \"Не указано\": \"\", \n \"Количество поражённых целей\": \"hitnum\", \n \"Количество отфильтрованных целей\": \"tarnum\", \n \"Изменение ресурса класса (с переполнением)\": \"propdiff\", \n \"Изменение ресурса класса (фактическое)\": \"proprealdiff\" \n}" },
            { "{\n \"Not specified type\": \"\", \n \"Neutral Buff\": \"0\", \n \"Buff\": \"1\", \n \"Debuff\": \"2\" \n}", "{\n \"Тип не указан\": \"\", \n \"Нейтральный бафф\": \"0\", \n \"Бафф\": \"1\", \n \"Дебафф\": \"2\" \n}" },
            { "{\n\"不指定类型\": \"\",\n\"中性Buff\": \"0\",\n\"增益Buff\": \"1\",\n\"减益Buff\": \"2\"\n}", "{\n \"Тип не указан\": \"\", \n \"Нейтральный бафф\": \"0\", \n \"Бафф\": \"1\", \n \"Дебафф\": \"2\" \n}" },
            { "{\n \"Calculate distance from capsule center\": \"False\", \n \"Calculate distance from capsule edge\": \"True\" \n}", "{\n \"Считать дистанцию от центра капсулы\": \"False\", \n \"Считать дистанцию от края капсулы\": \"True\" \n}" },
            { "{\n\"从胶囊体中心开始算距离\": \"False\",\n\"从胶囊体边缘开始算距离\": \"True\"\n}", "{\n \"Считать дистанцию от центра капсулы\": \"False\", \n \"Считать дистанцию от края капсулы\": \"True\" \n}" },
            { "{\n \"All (default value)\": \"All\", \n \"Enemy\": \"Enemy\", \n \"Friendly (excluding self)\": \"Friend\", \n \"Friendly\": \"FriendAndSelf\", \n}", "{\n \"Все (по умолчанию)\": \"All\", \n \"Враги\": \"Enemy\", \n \"Союзники (без себя)\": \"Friend\", \n \"Союзники и я\": \"FriendAndSelf\", \n}" },
            { "{\n\"全体(默认值)\":\"All\",\n\"敌方\": \"Enemy\",\n\"友方（不包含自己）\": \"Friend\",\n\"友方\": \"FriendAndSelf\",\n}", "{\n \"Все (по умолчанию)\": \"All\", \n \"Враги\": \"Enemy\", \n \"Союзники (без себя)\": \"Friend\", \n \"Союзники и я\": \"FriendAndSelf\", \n}" },
            { "{\n \"All players\": \"0\", \n \"Skill/buff holder\": \"1\", \n \"Locked target\": \"2\" \n}", "{\n \"Все игроки\": \"0\", \n \"Владелец навыка/баффа\": \"1\", \n \"Зафиксированная цель\": \"2\" \n}" },
            { "{\n\"全体玩家\": \"0\",\n\"技能/buff持有者\": \"1\",\n\"锁定目标\": \"2\"\n}", "{\n \"Все игроки\": \"0\", \n \"Владелец навыка/баффа\": \"1\", \n \"Зафиксированная цель\": \"2\" \n}" },
            { "{ \n \"Increase or decrease\": \"both\", \n \"Decrease\": \"down\", \n \"Increase\": \"up\" \n }", "{ \n \"Увеличение или уменьшение\": \"both\", \n \"Уменьшение\": \"down\", \n \"Увеличение\": \"up\" \n }" },
            { "{\n\"变多or变少\": \"both\",\n\"变少\": \"down\",\n\"变多\": \"up\"\n}", "{ \n \"Увеличение или уменьшение\": \"both\", \n \"Уменьшение\": \"down\", \n \"Увеличение\": \"up\" \n }" },
            { "{\n \"Big Windmill (joystick direction, full-body animation)\": \"0\", \n \"Wheel rolling (facing direction, full-body animation)\": \"1\", \n \"Skateboard shoes (joystick direction, half-body animation)\": \"2\", \n \"Pacing and scratching head (facing direction, full-body animation)\": \"3\" \n}", "{\n \"Большая мельница (направление джойстика, анимация тела)\": \"0\", \n \"Качение колеса (направление взгляда, анимация тела)\": \"1\", \n \"Коньки (направление джойстика, полукорпус)\": \"2\", \n \"Ходьба и почесывание затылка (направление взгляда, анимация тела)\": \"3\" \n}" },
            { "{\n\"大风车（摇杆方向，全身动画）\": \"0\",\n\"滚轮子（面向方向，全身动画）\": \"1\",\n\"滑板鞋（摇杆方向，半身动画）\": \"2\",\n\"踱步挠头（面向方向，全身动画）\": \"3\"\n}", "{\n \"Большая мельница (направление джойстика, анимация тела)\": \"0\", \n \"Качение колеса (направление взгляда, анимация тела)\": \"1\", \n \"Коньки (направление джойстика, полукорпус)\": \"2\", \n \"Ходьба и почесывание затылка (направление взгляда, анимация тела)\": \"3\" \n}" },
            { "{\n \"Skill/buff object target (holder/originator)\": \"0\", \n \"Level/scene as target\": \"1\", \n \"Objects in range as target\": \"2\", \n \"Target filter as target\": \"3\", \n \"Blackboard tarlist\": \"4\" \n}", "{\n \"Цель навыка/баффа (владелец/инициатор)\": \"0\", \n \"Уровень/сцена как цель\": \"1\", \n \"Объекты в радиусе как цель\": \"2\", \n \"Фильтр целей как цель\": \"3\", \n \"Список целей\": \"4\" \n}" },
            { "{\n\"技能/buff对象目标(持有者/始作俑者)\": \"0\",\n\"关卡/场景为目标\": \"1\",\n\"范围内对象为目标\": \"2\",\n\"目标筛选为目标\": \"3\",\n\"黑板 tarlist\":\"4\"\n}", "{\n \"Цель навыка/баффа (владелец/инициатор)\": \"0\", \n \"Уровень/сцена как цель\": \"1\", \n \"Объекты в радиусе как цель\": \"2\", \n \"Фильтр целей как цель\": \"3\", \n \"Список целей\": \"4\" \n}" },
            { "{ \n \"Press or release\": \"both\", \n \"Press\": \"down\", \n \"Release\": \"up\" \n }", "{ \n \"Нажатие или отпускание\": \"both\", \n \"Нажатие\": \"down\", \n \"Отпускание\": \"up\" \n }" },
            { "{\n\"按下或抬起\": \"both\",\n\"按下\": \"down\",\n\"抬起\": \"up\"\n}", "{ \n \"Нажатие или отпускание\": \"both\", \n \"Нажатие\": \"down\", \n \"Отпускание\": \"up\" \n }" },
            { "{\n\"None\": \"\", \n\"Slow\": \"SpeedDown\", \n\"Slumber\": \"Sleep\", \n\"Imprisonment\": \"Stuck\", \n\"Stun\": \"Dizzy\", \n\"Silence\": \"Silent\", \n\"Horror\": \"CharTerror\", \n\"Stiff\": \"Stiff\", \n\"Stagnation\": \"DodgeLimit\"\n}", "{\n\"Нет\": \"\", \n\"Замедление\": \"SpeedDown\", \n\"Сон\": \"Sleep\", \n\"Заточение\": \"Stuck\", \n\"Оглушение\": \"Dizzy\", \n\"Безмолвие\": \"Silent\", \n\"Ужас\": \"CharTerror\", \n\"Оцепенение\": \"Stiff\", \n\"Тягучесть\": \"DodgeLimit\"\n}" },
            { "{\n\"无\": \"\",\n\"减速\": \"SpeedDown\",\n\"睡眠\": \"Sleep\",\n\"禁锢\": \"Stuck\",\n\"眩晕\": \"Dizzy\",\n\"沉默\": \"Silent\",\n\"恐惧\": \"CharTerror\",\n\"僵直\": \"Stiff\",\n\"滞涩\": \"DodgeLimit\"\n}", "{\n\"Нет\": \"\", \n\"Замедление\": \"SpeedDown\", \n\"Сон\": \"Sleep\", \n\"Заточение\": \"Stuck\", \n\"Оглушение\": \"Dizzy\", \n\"Безмолвие\": \"Silent\", \n\"Ужас\": \"CharTerror\", \n\"Оцепенение\": \"Stiff\", \n\"Тягучесть\": \"DodgeLimit\"\n}" },
            { "{\n \"None\": \"\", \n \"Slow\": \"SpeedDown\", \n \"Sleep\": \"Sleep\", \n \"Imprisonment\": \"Stuck\", \n \"Stun\": \"Dizzy\", \n \"Silence\": \"Silent\", \n \"Stagnation\": \"DodgeLimit\" \n}", "{\n \"Нет\": \"\", \n \"Замедление\": \"SpeedDown\", \n \"Сон\": \"Sleep\", \n \"Заточение\": \"Stuck\", \n \"Оглушение\": \"Dizzy\", \n \"Безмолвие\": \"Silent\", \n \"Тягучесть\": \"DodgeLimit\" \n}" },
            { "{\n\"无\": \"\",\n\"减速\": \"SpeedDown\",\n\"睡眠\": \"Sleep\",\n\"禁锢\": \"Stuck\",\n\"眩晕\": \"Dizzy\",\n\"沉默\": \"Silent\",\n\"滞涩\": \"DodgeLimit\"\n}", "{\n \"Нет\": \"\", \n \"Замедление\": \"SpeedDown\", \n \"Сон\": \"Sleep\", \n \"Заточение\": \"Stuck\", \n \"Оглушение\": \"Dizzy\", \n \"Безмолвие\": \"Silent\", \n \"Тягучесть\": \"DodgeLimit\" \n}" },
            { "{\n \"None\": \"\", \n \"Knockback\": \"HitBack\", \n \"Knockdown\": \"HitDown\", \n \"Knockup\": \"HitFly\", \n \"Launch\": \"HitFloat\", \n \"Pull\": \"HitDrag\", \n \"Stagger\": \"HitStiff\" \n}", "{\n \"Нет\": \"\", \n \"Отбрасывание\": \"HitBack\", \n \"Сбивание с ног\": \"HitDown\", \n \"Подбрасывание\": \"HitFly\", \n \"Запуск\": \"HitFloat\", \n \"Притягивание\": \"HitDrag\", \n \"Оцепенение\": \"HitStiff\" \n}" },
            { "{\n\"无\": \"\",\n\"击退\": \"HitBack\",\n\"击倒\": \"HitDown\",\n\"击飞\": \"HitFly\",\n\"挑空\": \"HitFloat\",\n\"拖拽\": \"HitDrag\",\n\"僵直\": \"HitStiff\"\n}", "{\n \"Нет\": \"\", \n \"Отбрасывание\": \"HitBack\", \n \"Сбивание с ног\": \"HitDown\", \n \"Подбрасывание\": \"HitFly\", \n \"Запуск\": \"HitFloat\", \n \"Притягивание\": \"HitDrag\", \n \"Оцепенение\": \"HitStiff\" \n}" },
            { "{\n \"No restriction\": \"0\", \n \"Restrict skill resurrection\": \"1\", \n \"Restrict self-function resurrection\": \"2\", \n \"Prohibit resurrection\": \"3\" \n}", "{\n \"Без ограничений\": \"0\", \n \"Ограничить воскрешение навыком\": \"1\", \n \"Ограничить автовоскрешение\": \"2\", \n \"Запретить воскрешение\": \"3\" \n}" },
            { "{\n\"无限制\": \"0\",\n\"限制技能复活\": \"1\",\n\"限制自身功能复活\": \"2\",\n\"禁止复活\": \"3\"\n}", "{\n \"Без ограничений\": \"0\", \n \"Ограничить воскрешение навыком\": \"1\", \n \"Ограничить автовоскрешение\": \"2\", \n \"Запретить воскрешение\": \"3\" \n}" },
            { "{\n \"According to item table\": \"1\", \n \"Bound\": \"2\", \n \"Non-bound\": \"3\" \n}", "{\n \"По таблице предметов\": \"1\", \n \"Привязанный\": \"2\", \n \"Непривязанный\": \"3\" \n}" },
            { "{\n\"根据道具表\": \"1\",\n\"绑定\": \"2\",\n\"非绑定\": \"3\"\n}", "{\n \"По таблице предметов\": \"1\", \n \"Привязанный\": \"2\", \n \"Непривязанный\": \"3\" \n}" },
            { "{\n\"Listen for destruction (default)\": \"false\", \n\"Listen for Death Skill\": \"true\"\n}", "{\n\"Отслеживать уничтожение (по умолч.)\": \"false\", \n\"Отслеживать навык смерти\": \"true\"\n}" },
            { "{\n\"监听销毁（默认）\": \"false\",\n\"监听死亡技能\": \"true\"\n}", "{\n\"Отслеживать уничтожение (по умолч.)\": \"false\", \n\"Отслеживать навык смерти\": \"true\"\n}" },
            { "{\n\"Restrict to Walking Speed\": \"1\",\n\"Restrict to Running Speed\": \"2\"\n}", "{\n\"Ограничить скоростью шага\": \"1\",\n\"Ограничить скоростью бега\": \"2\"\n}" },
            { "{\n\"限制为走路速度\": \"1\",\n\"限制为跑步速度\": \"2\"\n}", "{\n\"Ограничить скоростью шага\": \"1\",\n\"Ограничить скоростью бега\": \"2\"\n}" },
            { "{\n \"Interrupt with state end\": \"0\", \n \"Interrupt with skill end\": \"1\", \n \"Do not interrupt\": \"2\" \n}", "{\n \"Прерывать по окончании состояния\": \"0\", \n \"Прерывать по окончании навыка\": \"1\", \n \"Не прерывать\": \"2\" \n}" },
            { "{\n\"随state结束而打断\": \"0\",\n\"随技能结束而打断\": \"1\",\n\"不打断\": \"2\"\n}", "{\n \"Прерывать по окончании состояния\": \"0\", \n \"Прерывать по окончании навыка\": \"1\", \n \"Не прерывать\": \"2\" \n}" },
            { "{\n \"Automatically cancel highlight after click\": \"0\", \n \"Do not automatically cancel highlight after click\": \"1\", \n}", "{\n \"Автоматически снимать подсветку по нажатию\": \"0\", \n \"Не снимать подсветку автоматически\": \"1\", \n}" },
            { "{\n点击后自动取消高亮: \"0\",\n点击后不会自动取消高亮: \"1\",\n}", "{\n \"Автоматически снимать подсветку по нажатию\": \"0\", \n \"Не снимать подсветку автоматически\": \"1\", \n}" },
            { "{\"Quantity of %ist Spell Field\"}", "{\"Количество магического поля №%i\"}" },
            { "{\"%i号法术场的数量\"}", "{\"Количество магического поля №%i\"}" },
            { "{\"Number of No. %i Traps\"}", "{\"Количество ловушек №%i\"}" },
            { "{\"%i号陷阱的数量\"}", "{\"Количество ловушек №%i\"}" },
            { "{\"Buff Tag%i\"}", "{\"Тег баффа %i\"}" },
            { "{\"Buff标签%i\"}", "{\"Тег баффа %i\"}" },
            { "{\"Buff tag %iDispel count\"}", "{\"Кол-во рассеиваний тега баффа %i\"}" },
            { "{\"Buff标签%i驱散数量\"}", "{\"Кол-во рассеиваний тега баффа %i\"}" },
            { "{\"Buff Type%i\"}", "{\"Тип баффа %i\"}" },
            { "{\"Buff类型%i\"}", "{\"Тип баффа %i\"}" },
            { "{ \"Mesh Name\" }", "{ \"Имя модели (Mesh)\" }" },
            { "{\"Mesh名称\"}", "{ \"Имя модели (Mesh)\" }" },
            { "{ \"X offset cm\", \"Y offset cm\", \"Z offset cm\" }", "{ \"Смещение X (см)\", \"Смещение Y (см)\", \"Смещение Z (см)\" }" },
            { "{\"X偏移cm\",\"Y偏移cm\",\"Z偏移cm\"}", "{ \"Смещение X (см)\", \"Смещение Y (см)\", \"Смещение Z (см)\" }" },
            { "{ \"Can be omitted\" }", "{ \"Можно пропустить\" }" },
            { "{\"可缺省\"}", "{ \"Можно пропустить\" }" },
            { "{\"Scene ID%i\"}", "{\"ID сцены %i\"}" },
            { "{\"场景ID%i\"}", "{\"ID сцены %i\"}" },
            { "{\"Coordinate X\", \"Coordinate Y\", \"Coordinate Z\"}", "{\"Координата X\", \"Координата Y\", \"Координата Z\"}" },
            { "{\"坐标X\",\"坐标Y\",\"坐标Z\"}", "{\"Координата X\", \"Координата Y\", \"Координата Z\"}" },
            { "{\"Entering 0 represents the currently equipped default mount\"}", "{\"0 означает текущего экипированного ездового питомца\"}" },
            { "{\"填0代表上当前装配的默认坐骑\"}", "{\"0 означает текущего экипированного ездового питомца\"}" },
            { "{\"Bullet%ifiring timing\"}", "{\"Время выстрела снаряда %i\"}" },
            { "{\"子弹%i发射时间点\"}", "{\"Время выстрела снаряда %i\"}" },
            { "{\"Bullet%i extra Pitch\"}", "{\"Доп. угол Pitch снаряда %i\"}" },
            { "{\"子弹%i额外Pitch\"}", "{\"Доп. угол Pitch снаряда %i\"}" },
            { "{\"Bullet %i Extra Yaw\"}", "{\"Доп. угол Yaw снаряда %i\"}" },
            { "{\"子弹%i额外Yaw\"}", "{\"Доп. угол Yaw снаряда %i\"}" },
            { "{\"Skill ID%i\"}", "{\"ID навыка %i\"}" },
            { "{\"技能ID%i\"}", "{\"ID навыка %i\"}" },
            { "{\"Skill Tag%i\"}", "{\"Тег навыка %i\"}" },
            { "{\"技能标签%i\"}", "{\"Тег навыка %i\"}" },
            { "{\"Skill Type%i\"}", "{\"Тип навыка %i\"}" },
            { "{\"技能类型%i\"}", "{\"Тип навыка %i\"}" },
            { "{\"Rotation Amount 1\", \"Rotation Amount 2\", \"Rotation Amount 3\"}", "{\"Угол вращения 1\", \"Угол вращения 2\", \"Угол вращения 3\"}" },
            { "{\"旋转量1\",\"旋转量2\",\"旋转量3\"}", "{\"Угол вращения 1\", \"Угол вращения 2\", \"Угол вращения 3\"}" },
            { "{\"Weight%i\"}", "{\"Вес %i\"}" },
            { "{\"权重%i\"}", "{\"Вес %i\"}" },
            { "{\"Tag %i\"}", "{\"Тег %i\"}" },
            { "{\"标签%i\"}", "{\"Тег %i\"}" },
            { "{\"Tag%iClear Buff Count\"}", "{\"Кол-во снятых баффов тега %i\"}" },
            { "{\"标签%i清除Buff数量\"}", "{\"Кол-во снятых баффов тега %i\"}" },
            { "{\"Slot Number\"=\"Skill ID\"}", "{\"Номер ячейки\"=\"ID навыка\"}" },
            { "{\"槽位编号\"=\"技能ID\"}", "{\"Номер ячейки\"=\"ID навыка\"}" },
            { "{\"Spell Field ID%i\"}", "{\"ID магического поля %i\"}" },
            { "{\"法术场ID%i\"}", "{\"ID магического поля %i\"}" },
            { "{\"The %ith Displacement destination\"}", "{\"Конечная точка перемещения №%i\"}" },
            { "{\"第%i个位移终点\"}", "{\"Конечная точка перемещения №%i\"}" },
            { "{\"Extra Pitch angle of the %ist bullet\"}", "{\"Доп. угол Pitch снаряда №%i\"}" },
            { "{\"第%i个子弹的额外Pitch角\"}", "{\"Доп. угол Pitch снаряда №%i\"}" },
            { "{\"Extra Yaw angle for the %ist bullet\"}", "{\"Доп. угол Yaw снаряда №%i\"}" },
            { "{\"第%i个子弹的额外Yaw角\"}", "{\"Доп. угол Yaw снаряда №%i\"}" },
            { "{\"Name of the %ist attribute\"}", "{\"Имя атрибута №%i\"}" },
            { "{\"第%i个属性名\"}", "{\"Имя атрибута №%i\"}" },
            { "{\"ID of the %ist Spell Field\"}", "{\"ID магического поля №%i\"}" },
            { "{\"第%i个法术场ID\"}", "{\"ID магического поля №%i\"}" },
            { "{\"Firing time of the %ist batch of bullets\"}", "{\"Время выстрела %i-й партии снарядов\"}" },
            { "{\"第%i批子弹发射时间点\"}", "{\"Время выстрела %i-й партии снарядов\"}" },
            { "{\"Type %i\"}", "{\"Тип %i\"}" },
            { "{\"类型%i\"}", "{\"Тип %i\"}" },
            { "{\"Trap ID%i\"}", "{\"ID ловушки %i\"}" },
            { "{\"陷阱ID%i\"}", "{\"ID ловушки %i\"}" },
            { "{\"Defaults to false. If true, the 4 restrictions above are invalid, but the whitelist takes effect\"}", "{\"По умолч. false. Если true, 4 ограничения выше не действуют, но активен белый список\"}" },
            { "{\"默认为false。若为true，上面4个限制无效，但白名单生效\"}", "{\"По умолч. false. Если true, 4 ограничения выше не действуют, но активен белый список\"}" },
            { "{{\"BuffID%i\",\"Buff Stacks%i\",\"Buff Duration%i\"}}", "{{\"ID баффа %i\",\"Стаки баффа %i\",\"Длительность баффа %i\"}}" },
            { "{{\"BuffID%i\",\"Buff层数%i\",\"Buff时长%i\"}}", "{{\"ID баффа %i\",\"Стаки баффа %i\",\"Длительность баффа %i\"}}" },
            { "{{ \"Bullet %i X offset cm\", \"Bullet %i Y offset cm\", \"Bullet %i Z offset cm\" }}", "{{ \"Смещение X снаряда %i (см)\", \"Смещение Y снаряда %i (см)\", \"Смещение Z снаряда %i (см)\" }}" },
            { "{{\"子弹%iX偏移cm\",\"子弹%iY偏移cm\",\"子弹%iZ偏移cm\"}}", "{{ \"Смещение X снаряда %i (см)\", \"Смещение Y снаряда %i (см)\", \"Смещение Z снаряда %i (см)\" }}" },
            { "{{\"Skill ID%i\", \"Level Increase\"}}", "{{\"ID навыка %i\", \"Повышение уровня\"}}" },
            { "{{\"技能ID%i\",\"增加等级\"}}", "{{\"ID навыка %i\", \"Повышение уровня\"}}" },
            { "{{\"Skill Type (see hover note)\", \"Increase Level\"}}", "{{\"Тип навыка (см. подсказку)\", \"Повышение уровня\"}}" },
            { "{{\"技能Type（参看悬停注释）\",\"增加等级\"}}", "{{\"Тип навыка (см. подсказку)\", \"Повышение уровня\"}}" },
            { "{{\"X offset of the %ind bullet in cm\", \"Y offset of the %ird bullet in cm\", \"Z offset of the %ith bullet in cm\"}}", "{{\"Смещение X %i-го снаряда (см)\", \"Смещение Y %i-го снаряда (см)\", \"Смещение Z %i-го снаряда (см)\"}}" },
            { "{{\"第%i个子弹的X偏移cm\",\"第%i个子弹的Y偏移cm\",\"第%i个子弹的Z偏移cm\"}}", "{{\"Смещение X %i-го снаряда (см)\", \"Смещение Y %i-го снаряда (см)\", \"Смещение Z %i-го снаряда (см)\"}}" },
            { "{{\"Attribute Name #%i\", \"Modified Value\"}}", "{{\"Имя атрибута №%i\", \"Изменённое значение\"}}" },
            { "{{\"第%i个属性名\",\"修改值\"}}", "{{\"Имя атрибута №%i\", \"Изменённое значение\"}}" },
            { "{{\"Resource name of the %ind button\", \"Corresponding Skill ID\", \"Corresponding keyboard key (can only be Q/W/E/R/A/S/D/F)\"}}", "{{\"Имя ресурса кнопки №%i\", \"Соответствующий ID навыка\", \"Клавиша клавиатуры (только Q/W/E/R/A/S/D/F)\"}}" },
            { "{{\"第%i个按键的资源名\",\"对应的技能ID\",\"对应的键盘按键（仅可填Q/W/E/R/A/S/D/F之一）\"}}", "{{\"Имя ресурса кнопки №%i\", \"Соответствующий ID навыка\", \"Клавиша клавиатуры (только Q/W/E/R/A/S/D/F)\"}}" },

            // Dev & Dungeon technical identifiers
            { "BattleZone_Butler", "ЗонаБитвы_Дворецкий" },
            { "BattleZone_管家", "ЗонаБитвы_Дворецкий" },
            { "Boss_Offspring Protection", "Босс_ЗащитаПотомства" },
            { "Boss_子嗣守护", "Босс_ЗащитаПотомства" },
            { "Boss_Core Tower", "Босс_БашняЯдра" },
            { "Boss_核心塔", "Босс_БашняЯдра" },
            { "Boss_Western Fantasy Dragon", "Босс_ЗападныйДракон" },
            { "Boss_西幻龙", "Босс_ЗападныйДракон" },
            { "Boss Fight_BossSpawner", "БоссБитва_СпавнерБосса" },
            { "Boss战_BossSpawner", "БоссБитва_СпавнерБосса" },
            { "Boss Battle_Ancestor Knight_Initial", "БоссБитва_РыцарьПредков_Начало" },
            { "Boss战_先祖骑士_初始", "БоссБитва_РыцарьПредков_Начало" },
            { "Boss Battle_Viscountess_Initial", "БоссБитва_Виконтесса_Начало" },
            { "Boss战_子爵夫人_初始", "БоссБитва_Виконтесса_Начало" },
            { "Boss Battle_Mythical Butler_Initial", "БоссБитва_МифическийДворецкий_Начало" },
            { "Boss战_神话管家_初始", "БоссБитва_МифическийДворецкий_Начало" },
            { "GTA-Mechanical Creation-Head-Return to Torso Explosion", "GTA-МехСоздание-Голова-ВзрывТорса" },
            { "GTA-机械造物-头部-返回躯干爆炸", "GTA-МехСоздание-Голова-ВзрывТорса" },
            { "GTA: Mechanical Creation: Pursuit Bullet", "GTA: МехСоздание: Самонаводящаяся пуля" },
            { "GTA-机械造物-追击子弹", "GTA: МехСоздание: Самонаводящаяся пуля" },
            { "GTA-Mechanical Creation-Lightning Ray", "GTA-МехСоздание-Молниевый луч" },
            { "GTA-机械造物-雷电射线", "GTA-МехСоздание-Молниевый луч" },
            { "GTA Fallen Priest Armor Break", "GTA Падший Священник Пробитие брони" },
            { "GTA堕落神父破防", "GTA Падший Священник Пробитие брони" },
            { "GTA Fallen Priest Armor Break 2", "GTA Падший Священник Пробитие брони 2" },
            { "GTA堕落神父破防2", "GTA Падший Священник Пробитие брони 2" },
            { "GTA Player Time Zero", "GTA Игрок Время Ноль" },
            { "GTA玩家时间零", "GTA Игрок Время Ноль" },
            { "ItrCol_Outside Switch", "ItrCol_Внешний переключатель" },
            { "ItrCol_开关外", "ItrCol_Внешний переключатель" },
            { "LuaList(Id(Trap)).", "LuaList(Id(Ловушка))." },
            { "LuaList(Id(陷阱))", "LuaList(Id(Ловушка))." },
            { "LuaList(IdGroup(Skill))", "LuaList(IdGroup(Навык))" },
            { "LuaList(IdGroup(技能))", "LuaList(IdGroup(Навык))" },
            { "LuaList(LuaTuple(IdGroup(Skill), Float())).", "LuaList(LuaTuple(IdGroup(Навык), Float()))." },
            { "LuaList(LuaTuple(IdGroup(技能),Float()))", "LuaList(LuaTuple(IdGroup(Навык), Float()))." },
            { "LuaList(LuaTuple(IdGroup(Skill), Int())).", "LuaList(LuaTuple(IdGroup(Навык), Int()))." },
            { "LuaList(LuaTuple(IdGroup(技能),Int()))", "LuaList(LuaTuple(IdGroup(Навык), Int()))." },
            { "LuaList(LuaTuple(Str(), IdGroup(Skill), Str())).", "LuaList(LuaTuple(Str(), IdGroup(Навык), Str()))." },
            { "LuaList(LuaTuple(Str(),IdGroup(技能),Str()))", "LuaList(LuaTuple(Str(), IdGroup(Навык), Str()))." },
            { "Npc_Teleport_Ancestor Knight", "Npc_Телепорт_РыцарьПредков" },
            { "Npc_传送_先祖骑士", "Npc_Телепорт_РыцарьПредков" },
            { "Npc_Teleport_Offspring Protection", "Npc_Телепорт_ЗащитаПотомства" },
            { "Npc_传送_子嗣守护", "Npc_Телепорт_ЗащитаПотомства" },
            { "Npc_Teleport_Butler", "Npc_Телепорт_Дворецкий" },
            { "Npc_传送_管家", "Npc_Телепорт_Дворецкий" },
            { "Poi0_Spawn Point", "Poi0_ТочкаВозрождения" },
            { "Poi0_重生点", "Poi0_ТочкаВозрождения" },
            { "Tri5_Recipe", "Tri5_Рецепт" },
            { "Tri5_配方", "Tri5_Рецепт" },
            { "Tri6_Monster", "Tri6_Монстр" },
            { "Tri6_怪物", "Tri6_Монстр" },
            { "May Manor_Offspring Protection_1 Target_Buff84008605", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008605" },
            { "五月庄园_子嗣守护_1目标_Buff84008605", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008605" },
            { "May Manor_Offspring Protection_1 Target_Buff84008606", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008606" },
            { "五月庄园_子嗣守护_1目标_Buff84008606", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008606" },
            { "May Manor_Offspring Protection_1 Target_Buff84008607", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008607" },
            { "五月庄园_子嗣守护_1目标_Buff84008607", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008607" },
            { "May Manor_Offspring Protection_1 Target_Buff84008608", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008608" },
            { "五月庄园_子嗣守护_1目标_Buff84008608", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008608" },
            { "May Manor_Offspring Protection_1 Target_Buff84008609", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008609" },
            { "五月庄园_子嗣守护_1目标_Buff84008609", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008609" },
            { "May Manor_Offspring Protection_1 Target_Buff84008612", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008612" },
            { "五月庄园_子嗣守护_1目标_Buff84008612", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008612" },
            { "May Manor_Offspring Protection_1 Target_Buff84008620", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008620" },
            { "五月庄园_子嗣守护_1目标_Buff84008620", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008620" },
            { "May Manor_Offspring Protection_1 Target_Buff84008621", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008621" },
            { "五月庄园_子嗣守护_1目标_Buff84008621", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008621" },
            { "May Manor_Offspring Protection_1 Target_Buff84008625", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008625" },
            { "五月庄园_子嗣守护_1目标_Buff84008625", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008625" },
            { "May Manor_Offspring Protection_1 Target_Buff84008626", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008626" },
            { "五月庄园_子嗣守护_1目标_Buff84008626", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008626" },
            { "May Manor_Offspring Protection_1 Target_Buff84008627", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008627" },
            { "五月庄园_子嗣守护_1目标_Buff84008627", "ПоместьеМэй_ЗащитаПотомства_1Цель_Бафф84008627" },
            { "Score_Personal", "Счёт_Личный" },
            { "分数_个人", "Счёт_Личный" },
            { "Score_Total", "Счёт_Общий" },
            { "分数_总计", "Счёт_Общий" },
            { "Create_Bullet", "Создание_Снаряд" },
            { "创建_子弹", "Создание_Снаряд" },
            { "Create_Trap", "Создание_Ловушка" },
            { "创建_陷阱", "Создание_Ловушка" },
            { "Dungeon_May Manor_Outer City_Main Flow_General", "Подземелье_ПоместьеМэй_ВнешнийГород_ОсновнойЭтап" },
            { "副本_五月庄园_外城_主流程_通用", "Подземелье_ПоместьеМэй_ВнешнийГород_ОсновнойЭтап" },
            { "Function_Hit Vine", "Функция_ПопаданиеПоЛозе" },
            { "功能_命中藤蔓", "Функция_ПопаданиеПоЛозе" },
            { "Function_Heal", "Функция_Исцеление" },
            { "功能_回血", "Функция_Исцеление" },
            { "Function_Already Aimed", "Функция_УжеПрицелился" },
            { "功能_已被瞄准", "Функция_УжеПрицелился" },
            { "Function_Thug Shield", "Функция_ЩитБандита" },
            { "功能_打手护盾", "Функция_ЩитБандита" },
            { "Function_Carry Aiming Box", "Функция_НестиРамкуПрицела" },
            { "功能_携带瞄准框", "Функция_НестиРамкуПрицела" },
            { "Function_Gunman Shield", "Функция_ЩитСтрелка" },
            { "功能_枪手护盾", "Функция_ЩитСтрелка" },
            { "Function_Alchemy Insight_Count", "Функция_АлхимическийОпыт_Счётчик" },
            { "功能_炼金心得_计数", "Функция_АлхимическийОпыт_Счётчик" },
            { "Function_Backstab", "Функция_УдарВспину" },
            { "功能_背刺", "Функция_УдарВспину" },
            { "Function_Trigger Skill", "Функция_ТриггерНавыка" },
            { "功能_触发技能", "Функция_ТриггерНавыка" },
            { "Function_Sports Meet Attack_Sequence 4", "Функция_АтакаСпортивногоСобрания_Последовательность4" },
            { "功能_运动会发动攻击_顺序4", "Функция_АтакаСпортивногоСобрания_Последовательность4" },
            { "Pillar_After Teleport", "Колонна_ПослеТелепорта" },
            { "台柱_传送后", "Колонна_ПослеТелепорта" },
            { "View_Attack Box", "Просмотр_ХитбоксАтаки" },
            { "查看_攻击盒", "Просмотр_ХитбоксАтаки" },
            { "Mark_Offspring Protection_Hard", "Метка_ЗащитаПотомства_Сложно" },
            { "标记_子嗣守护本体_困难", "Метка_ЗащитаПотомства_Сложно" },
            { "Mark_Phantom Tear_Target 1", "Метка_ФантомныйРазрыв_Цель1" },
            { "标记_幻影撕裂_点名1", "Метка_ФантомныйРазрыв_Цель1" },
            { "Mark_Phantom Tear_Target 2", "Метка_ФантомныйРазрыв_Цель2" },
            { "标记_幻影撕裂_点名2", "Метка_ФантомныйРазрыв_Цель2" },
            { "Mark_Phantom Tear_Target 3", "Метка_ФантомныйРазрыв_Цель3" },
            { "标记_幻影撕裂_点名3", "Метка_ФантомныйРазрыв_Цель3" },
            { "Mark_Tear Earth", "Метка_РазрывЗемли" },
            { "标记_撕裂大地", "Метка_РазрывЗемли" },
            { "Mark_Alchemy Insights_Boss_Ley Line", "Метка_АлхимическийОпыт_Босс_ЖилаЗемли" },
            { "标记_炼金心得_Boss_地脉", "Метка_АлхимическийОпыт_Босс_ЖилаЗемли" },
            { "Mark_Alchemy Insights_Boss_Greatsword", "Метка_АлхимическийОпыт_Босс_ДвуручныйМеч" },
            { "标记_炼金心得_Boss_大剑", "Метка_АлхимическийОпыт_Босс_ДвуручныйМеч" },
            { "Mark_Alchemy Insights_Boss_Battle Axe", "Метка_АлхимическийОпыт_Босс_БоевойТопор" },
            { "标记_炼金心得_Boss_战斧", "Метка_АлхимическийОпыт_Босс_БоевойТопор" },
            { "Mark_Golem Earth Tremor_Target 1", "Метка_ДрожьЗемлиГолема_Цель1" },
            { "标记_魔像大地震颤_点名1", "Метка_ДрожьЗемлиГолема_Цель1" },
            { "Mark_Golem Earth Tremor_Target 2", "Метка_ДрожьЗемлиГолема_Цель2" },
            { "标记_魔像大地震颤_点名2", "Метка_ДрожьЗемлиГолема_Цель2" },
            { "Mark_Golem Earth Tremor_Target 3", "Метка_ДрожьЗемлиГолема_Цель3" },
            { "标记_魔像大地震颤_点名3", "Метка_ДрожьЗемлиГолема_Цель3" },
            { "Supply Box-Surround Effect-plus", "ЯщикПрипасов-КруговойЭффект-плюс" },
            { "物资箱-环绕特效-plus", "ЯщикПрипасов-КруговойЭффект-плюс" },
            { "Effect_Teleport_Ancestor Knight", "Эффект_Телепорт_РыцарьПредков" },
            { "特效_传送_先祖骑士", "Эффект_Телепорт_РыцарьПредков" },
            { "Effect_Teleport_Offspring Protection", "Эффект_Телепорт_ЗащитаПотомства" },
            { "特效_传送_子嗣守护", "Эффект_Телепорт_ЗащитаПотомства" },
            { "Effect_Teleport_Butler", "Эффект_Телепорт_Дворецкий" },
            { "特效_传送_管家", "Эффект_Телепорт_Дворецкий" },
            { "Effect_Teleport NPC", "Эффект_Телепорт_NPC" },
            { "特效_传送npc", "Эффект_Телепорт_NPC" },
            { "Effect_Trissy_Exit", "Эффект_Выход_Трис" },
            { "特效_特莉丝出口", "Эффект_Выход_Трис" },
            { "God Abandoned 7 Battle Spawn", "ЗемляБогов 7 Битва Появление" },
            { "神弃7战生", "ЗемляБогов 7 Битва Появление" },
            { "Secret Realm 3_Mob Fight", "ТайноеЦарство 3_БитваСМонстрами" },
            { "秘境3_小怪战", "ТайноеЦарство 3_БитваСМонстрами" },
            { "Mental Plague Buff Roguelike AOE Attack Box", "Хитбокс АОЕ атаки Баффа Ментальной Чумы" },
            { "精神瘟疫buff肉鸽AOE攻击盒", "Хитбокс АОЕ атаки Баффа Ментальной Чумы" },
            { "Effect_Knockback Shockwave", "Эффект_УдарнаяВолнаОтбрасывания" },
            { "表现_击退冲击波", "Эффект_УдарнаяВолнаОтбрасывания" },
            { "Performance_Wall_Ready", "Стена_Готовность" },
            { "表现_墙_就绪", "Стена_Готовность" },
            { "Performance_Holding Sword", "Стойка_ДержитМеч" },
            { "表现_持剑", "Стойка_ДержитМеч" },
            { "Performance_Holding Axe", "Стойка_ДержитТопор" },
            { "表现_持斧", "Стойка_ДержитТопор" },
            { "Performance_Model Hide_Invisibility Mechanism", "Механизм_СкрытиеМодели_Невидимость" },
            { "表现_模型隐藏_隐身机制", "Механизм_СкрытиеМодели_Невидимость" },
            { "Performance_Model Hidden_Non-Invisibility Mechanism", "Механизм_СкрытиеМодели_БезНевидимости" },
            { "表现_模型隐藏_非隐身机制", "Механизм_СкрытиеМодели_БезНевидимости" },
            { "Effect_Targeted AOE", "Эффект_ПрицельноеАОЕ" },
            { "表现_点名AOE", "Эффект_ПрицельноеАОЕ" },
            { "Effect_Alchemy Insight_Ley Line", "Эффект_АлхимическийОпыт_ЖилаЗемли" },
            { "表现_炼金心得_地脉", "Эффект_АлхимическийОпыт_ЖилаЗемли" },
            { "Effect_Alchemy Insight_Battle Axe", "Эффект_АлхимическийОпыт_БоевойТопор" },
            { "表现_炼金心得_战斧", "Эффект_АлхимическийОпыт_БоевойТопор" },
            { "Trigger_Offspring Protection", "Триггер_ЗащитаПотомства" },
            { "触发器_子嗣守护", "Триггер_ЗащитаПотомства" },
            { "Lock_Rectangular AOE 01", "Захват_ПрямоугольноеАОЕ 01" },
            { "锁定_矩形AOE01", "Захват_ПрямоугольноеАОЕ 01" },
            { "Lock_Rectangular AOE 02", "Захват_ПрямоугольноеАОЕ 02" },
            { "锁定_矩形AOE02", "Захват_ПрямоугольноеАОЕ 02" }
        };

        var fileLines = new List<string>(File.ReadAllLines(ruPath, Encoding.UTF8));
        var keyToLine = new Dictionary<string, int>(StringComparer.Ordinal);

        for (int i = 0; i < fileLines.Count; i++)
        {
            string t = fileLines[i].Trim();
            if (t.StartsWith("[\"") && (t.EndsWith("\",") || t.EndsWith("\"")))
            {
                int delim = t.IndexOf("\"] = \"");
                if (delim > 0)
                {
                    string k = t.Substring(2, delim - 2);
                    keyToLine[k] = i;
                }
            }
        }

        int updated = 0;
        int appended = 0;
        var pending = new List<string>();

        foreach (var kvp in map)
        {
            string cleanK = CleanLua(kvp.Key);
            string cleanV = CleanLua(kvp.Value);

            if (keyToLine.ContainsKey(cleanK))
            {
                fileLines[keyToLine[cleanK]] = string.Format("    [\"{0}\"] = \"{1}\",", cleanK, cleanV);
                updated++;
            }
            else
            {
                pending.Add(string.Format("    [\"{0}\"] = \"{1}\",", cleanK, cleanV));
                appended++;
            }
        }

        if (pending.Count > 0)
        {
            int lastBrace = fileLines.FindLastIndex(x => x.Trim() == "}");
            if (lastBrace < 0) lastBrace = fileLines.Count;
            fileLines.InsertRange(lastBrace, pending);
        }

        Console.WriteLine(string.Format("Updated: {0}, Appended: {1}", updated, appended));
        File.WriteAllLines(ruPath, fileLines, new UTF8Encoding(false));
        Console.WriteLine("Saved updated file!");
    }

    static string CleanLua(string s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        string r = s.Replace("\r\n", "\n").Replace("\r", "");
        r = r.Replace("\\n", "\n").Replace("\\t", "\t");
        r = r.Replace("\\\"", "\"");
        r = r.Replace("\"", "\\\"");
        r = r.Replace("\n", "\\n").Replace("\t", "\\t");
        return r;
    }
}
